POST https://node-do-zero-jpn4.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Este é o video 01",
  "duration": 180
}

###

GET https://node-do-zero-jpn4.onrender.com/videos

###

PUT https://node-do-zero-jpn4.onrender.com/videos/849efd21-ff1a-4f10-b826-688d5dca7b4a
Content-Type: application/json

{
  "title": "Video 02",
  "description": "Este é o video 02",
  "duration": 180
}

###

DELETE https://node-do-zero-jpn4.onrender.com/videos/849efd21-ff1a-4f10-b826-688d5dca7b4a
